[package]
name = "inboisu"
authors = [ "mkpoli <mkpoli@mkpo.li>" ]
entrypoint = "lib.typ"
license = "MIT"
version = "0.3.0"
description = "Inboisu is a tool for creating Japanese invoices."
keywords = [ "invoice", "japanese", "banking" ]
categories = [ "layout", "office" ]
disciplines = [ "business" ]
repository = "https://github.com/mkpoli/typst-inboisu"

[template]
entrypoint = "main.typ"
path = "template"
thumbnail = "thumbnail.png"